### ISSUE TITLE
rsyslog.conf - command log template inconsistency

### ISSUE THREAD

**Issue by srajgopalan** [aaron-613/solace-logging-config#1]
In the rsyslog.conf file, the command log template has a typo(?) in the path name where you are going to write files. It reads:

"/var/log/solace.syslog/router.%HOSTNAME%/command.log")

while all other templates log to "/var/log/solace.rsyslog/router.%HOSTNAME%/<name>.log

so: s/solace.syslog/solace.rsyslog/ in the command log template

**Comment by aaron-613** [comment]
Fixed!  Thanks.
