### ISSUE TITLE
Missing logs while log rotation

### ISSUE THREAD

**Issue by Ravikiran7161** [aaron-613/solace-logging-config#3]
Suppose the rsyslog writing solace logs continuously to log files, when we run log rotation job at the time of writing, do we miss any data? How log rotate handles it?

**Comment by aaron-613** [comment]
Hey @Ravikiran7161 .  Thanks for the comment.  Or issue?  I've always wondered if anyone has actually ever looked at these files.  I wrote these rules a long time ago for a Solace customer.

Anyhow, I honestly don't know 100% the answer to that... that would be a question for someone that knows rsyslog and logrotate better than me.  I've never see it drop log entries during a rotation.  It would be one heck of a race condition.  I've done some Googling, and it looks like there are ways to ensure this doesn't happen.

**Comment by Ravikiran7161** [comment]
What I found about logrotation.. 
rsyslog open e.g. /var/log/syslog, gets a file descriptor and writes to this file.
logrotate rotates/renames old and not in use logfiles /var/log/syslog.X -> /var/log/syslog.X+1
logrotate renames (see rename(2)) /var/log/syslog to /var/log/syslog.1 and creates an empty file /var/log/syslog
rsyslog still has the renamed file open and continues writing to it via the file descriptor (not via the path)
logrotate runs the postrotate command (in case of rsyslog e.g. systemctl kill -s HUP rsyslog.service), so rsyslog closes the old file descriptor and opens a new one with the path of /var/log/syslog, which is now an empty file

-when rsyslog recieves a message it adds it to a queue (if the queue gets full it
stops accepting messages).
-when it gets a HUP, it continues to accept messages and closes it's outputs, it
does not loose any messages in the process.

**Comment by Ravikiran7161** [comment]
Is there any way to monitor the rsyslog service that it is always running and receiving messages? if not send alerts ?
Any suggestions?

**Comment by aaron-613** [comment]
Closing, all Solace-related questions have been answered.
