### ISSUE TITLE
Missing log severity in the remote syslog servers

### ISSUE THREAD

**Issue by Michelgiggs** [aaron-613/solace-logging-config#4]
Hey Aaron,
On our solace appliances we have configured to send logs to our syslog servers. We are receiving them but in the log messages the log level is missing. Do you have any idea why the logs not printing log level/severity on our remote syslog servers?
We can see log level on the solace appliance.    

Thank you

**Comment by aaron-613** [comment]
The level/severity is definitely being sent by the appliances.  It is encoded along with the facility in the Priority field, which is part of the Syslog specification.  See: https://tools.ietf.org/html/rfc5424#section-6.2.1

There must be some filtering or something happening in your syslog server.  Or just the level not getting printed.  Can you see the priority at least?

Which server are you using?  Can share config?

**Comment by Michelgiggs** [comment]
I am using centos7. Below is the config, am I missing anything?

module(load="imudp" threads="2")
input(type="imudp" port="40510" ruleset="sol-rsyslog" RateLimit.Interval="0" RateLimit.Burst="0")
input(type="imudp" port="40511" ruleset="sol-rsyslog" RateLimit.Interval="0" RateLimit.Burst="0")

$FileCreateMode 0644
$DirCreateMode 0755

template(name="CmdLog"    type="string" string="/xx/xx/xx/%HOSTNAME%/command/command.log")
template(name="EventLog"  type="string" string="/xx/xx/xx/%HOSTNAME%/event/event.log")
template(name="SystemLog"  type="string" string="/xx/xx/xx/%HOSTNAME%/system/system.log")

ruleset (name="sol-rsyslog") {
if ($syslogfacility-text == 'local1') then {
 ?CmdLog
 stop
 }

# event log
if ($syslogfacility-text == 'local3') then {
 ?EventLog
 stop
 }

# sysyem log
if ($syslogfacility-text == 'local4') then {
 ?SystemLog
 stop
 }
}

**Comment by aaron-613** [comment]
Can you edit your post and use the `code block`?  Makes it easier for reading, doesn't get converted to Markdown.

Anyhow, so this looks like rsyslog, yes?  I'm quite rusty, but it doesn't look like you specify any formatting to use when emitting the event log.  In my rsyslog config, you can see the line:

`template(name="EventLogFormat" type="string" string="%TIMESTAMP:1:23:date-rfc3339%%TIMESTAMP:27:$:date-rfc3339% <%syslogseverity-text%> %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")`

Then when it is time to emit the event log, I do: `      ?EventLog; EventLogFormat`

**Comment by Michelgiggs** [comment]
Yes its rsyslog. I added the log format template. Its printing the log level now.
Many thanks to you :)
